server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: prj-customermngt-bank
          uri: http://localhost:8085/
          predicates:
            - Path=/person/**
